USE db_rpg

SET NOCOUNT ON

MERGE dbo.tb_criticidade AS destino
USING	(
		VALUES
			 (101,'Aumenta o dano causado em 1')
			,(102,'Aumenta o dano causado em 5')
			,(103,'Aumenta o dano causado em 8')
			,(104,'Aumenta o dano causado em 11')
			,(105,'Aumenta o dano causado em 15')
			,(106,'Recebe Inspiração')
			,(107,'Recebe Surto de Ação somente nesse turno')
			,(108,'Pode conjurar uma magia livremente nesse turno, sem gastar slots de magia')
			,(109,'Concede 20% de XP extra nessa sessão')
			,(110,'Recebe um ponto de trama ou recebe uma inspiração de bardo')
			,(111,'Concede Escudo da Fé')
			,(112,'Concede Benção a três criaturas aleatórias')
			,(113,'Concede Palavra Curativa a todos os aliados')
			,(114,'Concede Ajuda a três aliados aleatórios')
			,(115,'Concede Sinal de Esperança a todos os aliados')
			,(116,'Meteoritos caem em todos os oponentes adjacentes ao alvo prioritário (2d6 de dano, DES para 1/2)')
			,(117,'Um relâmpago acerta a criatura atingida')
			,(118,'Uma armadura de gelo circundeia o atacante, concedendo 10 de vida temporária e causando a mesma quantia em dano para quem o atingir')
			,(119,'Relâmpagos caem em direção a sua lâmina brandida, causando 1d6 de dano extra de raio até o fim do combate')
			,(120,'Uma nevasca cai impediosamente nos inimigos, causando 2d6 de dano em todos, em um alcance de 6mts de diâmetro')
			,(121,'O atacante fica imune a efeitos mágicos até a próxima magia acertá-lo ou até o fim do combate')
			,(122,'A arma fica encantada com gelo, diminuindo a distância de deslocamento em 50% de todas as criatuas que você atingir durante um turno, até o fim do combate')
			,(123,'A criatura atingida é movida para um plano elemental por 10 turnos, CD15 SAB para retornar')
			,(124,'O atacante passa a enxergar o invisível até o fim do combate')
			,(125,'O atacante pode se teleportar a até 18mts até o fim deste turno, sem gerar ataques de oportunidade')
			,(126,'Dobra seu atributo de dano para este ataque')
			,(127,'O ataque reduz a CA em 2 por conta de uma forte perfuração')
			,(128,'Você acerta com o ataque crítico em uma outra criatura adjacente a esta criatura')
			,(129,'O próximo ataque causado no oponente causará 10 de dano extra')
			,(130,'Quebra da Armadura do oponente')
			,(131,'Consegue pegar um item aleatório do oponente')
			,(132,'Consegue roubar 1d20*(nível do inimigo) em Ouro')
			,(133,'Desarma o possível escudo do inimigo e a derruba no chão, caso não tenha, dá uma rasteira causando 1d4 de dano e derruba o inimigo no chão')
			,(134,'Desarma a arma do oponente e a derruba')
			,(135,'Desarma a arma do oponente e a pega pra si')
			,(136,'Triplica os dados de dano')
			,(137,'Dobra o dano causado em vez de dobrar os dados')
			,(138,'Adiciona um dado extra no dano causado, sempre o maior dado disponível para dano, e adicione +5 no seu dano final')
			,(139,'Triplica o dano em vez de dobrar os dados')
			,(140,'Caso seu primeiro próximo ataque acerte o adversário, ele também será um ataque crítico')
			,(141,'Dá vantagem para os outros aliados atacarem o mesmo alvo até o seu próximo turno')
			,(142,'Dá desvantagem em todos os próximos ataques do turno subsequente do adversário')
			,(143,'Pode se movimentar mais 9mts durante esse turno')
			,(144,'Pode realizar uma ação de desengage livremente nesse turno')
			,(145,'Pode realizar um novo ataque extra')
			,(146,'Ferimento interno grave que causa 1d12 de dano por turno')
			,(147,'Perda de um braço')
			,(148,'Perda de uma perna')
			,(149,'Perda de um olho')
			,(150,'K.O Instantâneo')
			,(201,'Seu erro é tanto que você desmaia de desgosto. CD15 de INT para acordar')
			,(202,'O personagem ao errar acaba atraindo pra si um campo magnético. Qualquer magia  ou projétil será direcionado pra si durante 1d6 turnos')
			,(203,'Todas as armadilhas do cômodo que o personagem se encontra é ativado, curiosamente direcionada pra si')
			,(204,'Um clone do inimigo surge adjacente ao alvo primário, usando os mesmos status')
			,(205,'O personagem se torna um ponto de gravidade humano. Todos os personagens se movem em direção a ele, necessitando em todo turno realizar um teste de Atletismo CD 18 para poder se mover livremente')
			,(206,'A próxima magia  conjurada será aleatória, conjurada em um alvo aleatório, não podendo ser cancelada voluntariamente')
			,(207,'As armas dos inimigos dobram de tamanho, recebendo 1d4 de dano bônus')
			,(208,'Todas as magias que o atacante usar durante este dia serão direcionadas para si, exceto magias que o beneficiem. Estas serão direcionadas aos inimigos')
			,(209,'O personagem irá chamar a atenção de seus inimigos, sendo o prinicipal foco de ataques,e xceto quando não houver possibilidade disto ocorrer')
			,(210,'O personagem deverá designar um aliado aleatório em segredo para se transformar em um vaso de planta por 1d6 turnos')
			,(211,'O atacante sente a obrigação de se provar, se movimentando em direção ao maior número de inimigos possíveis nesse turno, ou, caso ele já tenha gasto parte ou totalmente sua movimentação, no próximo turno')
			,(212,'O dedo mindinho bate numa rocha, recebendo 1d2 de dano e reduzindo a movimentação em 50% no próximo turno. Além disso, ele sai pulando')
			,(213,'Você pisa em um formigueiro, tomando 1d4 de dano por turno até o fim do combate e reduzindo seu deslocamento em 3mts')
			,(214,'O personagem fica preso em um lamaçal, ficando incapaz de se mover. CD10+LV do usuário em FOR para tentar sair')
			,(215,'A armadura se solta durante o ataque, desconsiderando totalmente a CA durante esse período')
			,(216,'10% das moedas de ouro do atacante criam asas e voam para o além')
			,(217,'A mochila se rompe com o ataque')
			,(218,'Você fica com soluço e até o final do combate, você demorará um turno extra pra conjurar uma magia')
			,(219,'Uma ilusão toma conta de sua mente, fazendo-o atacar um aliado imediatamente de qualquer forma possível')
			,(220,'Sua arma começa a provocar os inimigos, fazendo com que eles te ataquem com vantagem por 1d6 turnos')
			,(221,'O ombro do atacante se desloca, reduzindo o bônus de FOR/DES nos ataques e danos à 0')
			,(222,'O atacante sente fortes câimbras e tem seu deslocamento reduzido pela metade')
			,(223,'O personagem sente forte tontura, reduzindo o bônus de DES na CA para 0')
			,(224,'O atacante torce o calcanhar, reduzindo seu deslocamento por 1d6 turnos')
			,(225,'O usuário arranha suas cordas vocais, ficando incapacitado de conjurar magias que necessitem de Verbal')
			,(226,'Queda de arma à 1,5mt de distância a escolha do jogador')
			,(227,'Queda de arma à 3mts de distância a escolha do jogador')
			,(228,'A arma causará 50% de dano apenas até que ela seja consertada')
			,(229,'A arma cai em um plano astral ')
			,(230,'A arma quebra e nunca mais poderá ser utilizada')
			,(231,'O personagem recebe desvantagem nos ataques no próximo turno')
			,(232,'Um inimigo (a escolha do inimigo) se aproxima até 9mts do player que teve falha crítica. Se ele conseguir ficar do lado do inimigo, pode realizar um ataque')
			,(233,'Tamanha a esquiva de seu oponente, você fica com o status Amedrontado até o fim do combate contra aquela criatura')
			,(234,'O inimigo lhe agarra após a defesa sucessiva')
			,(235,'O inimigo lhe provoca após sua falha, lhe forçando até o fim do combate a atacar apenas ele, com desvantagem')
			,(236,'O personagem se machuca no ataque, ficando caído e recebendo 1d8 de dano')
			,(237,'O personagem se auto-acerta, causando seu dano padrão')
			,(238,'O adversário poderá contra-atacar o ataque falho')
			,(239,'O ataque falho acerta a própria armadura, reduzindo a CA concedida pela metade (arredondado para baixo)')
			,(240,'A iniciativa passa imediatamente para o oponente atacado')
			,(241,'O personagem escorrega numa poça de água, ficando caído até o final do seu turno')
			,(242,'O inimigo conjura Escudo Arcano automaticamente e ainda por cima errando o ataque')
			,(243,'Um goblin arcano rouba um item aleatório do personagem que errou')
			,(244,'Um feixe de luz originário da Agréstia das Fadas lhe cega por 1d6 turnos')
			,(245,'O personagem acaba entrando  em um plano elemental por acidente, permanecendo lá por 1d4 turnos')
			,(246,'Todos os inimigos adjacentes a você lhe atacarão após sua falha')
			,(247,'Você conjura um scroll mágico da lista de itens mágicos em si mesmo')
			,(248,'Um relâmpago cai na sua cabeça')
			,(249,'Um elemental aleatório surgirá adjacente a pessoa que ativou este efeito')
			,(250,'O personagem deve rolar imediatamente a tabela de Magia Selvagem')
		)
		AS origem (cd_acerto_erro, desc_criticidade)

ON (destino.cd_acerto_erro = origem.desc_criticidade)

WHEN MATCHED THEN

	UPDATE SET
	 destino.cd_acerto_erro		= origem.cd_acerto_erro
	,destino.desc_criticidade	= origem.desc_criticidade

WHEN NOT MATCHED BY TARGET THEN

	INSERT (cd_acerto_erro, desc_criticidade)
	VALUES (origem.cd_acerto_erro, origem.desc_criticidade)

WHEN NOT MATCHED BY SOURCE THEN

	DELETE;
